- ignore: {name: "Use <$>"}
- warn: {name: Use explicit module import list}
- warn: {name: Use module export list}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Redundant if"}
- ignore: {name: "Use camelCase"}
- ignore: {name: "Eta reduce"}
